# ===================================================================
# CONFIGURACIÓN GENERAL DEL MICROSERVICIO DE PREREGISTRO
# ===================================================================
spring.application.name=ms-preregistro
server.port=8084

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (PostgreSQL - DB Trámites)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_tramites
spring.datasource.username=postgres
spring.datasource.password=tu_password_de_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURACIÓN DE APACHE KAFKA (Publicación de eventos de cruce)
# ===================================================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ===================================================================
# CONFIGURACIÓN DE EUREKA (Registro de servicio)
# ===================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===================================================================
# CONFIGURACIÓN DE LOGS
# ===================================================================
server.error.include-message=always
logging.level.root=INFO
logging.level.com.frontintel.aduanas.ms_preregistro=DEBUG
