# ===================================================================
# CONFIGURACIÓN GENERAL DEL MICROSERVICIO DE OPERACIONES
# ===================================================================
spring.application.name=ms-operaciones
server.port=8087

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (PostgreSQL - DB Operaciones)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_operaciones
spring.datasource.username=postgres
spring.datasource.password=tu_password_de_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURACIÓN DE EUREKA
# ===================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===================================================================
# CONFIGURACIÓN DE LOGS
# ===================================================================
server.error.include-message=always
logging.level.root=INFO
logging.level.com.frontintel.aduanas.ms_operaciones=DEBUG
