Properties
# ===================================================================
# CONFIGURACIÓN GENERAL DEL MICROSERVICIO
# ===================================================================
spring.application.name=ms-autenticacion
server.port=8081

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (PostgreSQL - DB Usuarios)
# ===================================================================
# URL de conexión a PostgreSQL (Asegúrate de que la base de datos 'db_usuarios' exista en tu Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuarios
spring.datasource.username=postgres
spring.datasource.password=tu_password_de_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# 'update' permite que Hibernate cree las tablas de forma automática en Postgres si no existen
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Spring las sentencias SQL reales que se ejecutan
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURACIÓN DE VALIDACIONES (Mensajes de error limpios)
# ===================================================================
# Evita que Spring envíe trazas de error gigantescas al cliente en Postman
server.error.include-message=always
server.error.include-binding-errors=always

# ===================================================================
# CONFIGURACIÓN DE LOGS
# ===================================================================
logging.level.root=INFO
logging.level.com.frontintel.aduanas.ms_autenticacion=DEBUG