# ===================================================================
# CONFIGURACIÓN GENERAL DEL MICROSERVICIO
# ===================================================================
spring.application.name=ms-notificaciones
server.port=8083

# ===================================================================
# CONFIGURACIÓN DE APACHE KAFKA (Bus de Eventos Binacional)
# ===================================================================
# Dirección del servidor de Kafka (Apunta al puerto por defecto 9092)
spring.kafka.bootstrap-servers=localhost:9092

# Identificador único del grupo de consumidores para este servicio
spring.kafka.consumer.group-id=grupo-notificaciones

# Estrategia de lectura si no hay un offset previo (lee desde el inicio del tópico)
spring.kafka.consumer.auto-offset-reset=earliest

# Clases encargadas de transformar los bytes de la red a tipos de datos Java
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# ===================================================================
# CONFIGURACIÓN DE REDIS (Base de Datos en Memoria para Fila Virtual)
# ===================================================================
# Dirección y puerto de tu contenedor o servidor Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Opcional: Tiempo de espera para las conexiones (en milisegundos)
spring.data.redis.timeout=2000

# ===================================================================
# CONFIGURACIÓN DEL SERVIDOR DE CORREOS (Notificaciones SMTP)
# ===================================================================
# Para pruebas locales se recomienda usar Mailtrap, para producción SMTP de la aduana
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=tu_usuario_de_mailtrap
spring.mail.password=tu_password_de_mailtrap
spring.mail.default-encoding=UTF-8

# Propiedades adicionales de seguridad para el protocolo de correo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===================================================================
# CONFIGURACIÓN DE LOGS Y LOGGING
# ===================================================================
# Permite ver en la consola los mensajes informativos del flujo de Kafka y Redis
logging.level.root=INFO
logging.level.com.frontintel.aduanas.ms_notificaciones=DEBUG